version: "3.9"
services:
  pyspark:
    build: ./ # use the current directory as the source
    ports:
      - 8888:8888 # publish the port 8888 to the host
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./mock:/home/jovyan/mock
    environment:
      #- PYSPARK_SUBMIT_ARGS="--packages datastax:spark-cassandra-connector:3.3.0"
      - JUPYTER_ENABLE_LAB=yes
    command: start-notebook.sh --NotebookApp.token=''
    deploy:
      resources:
        limits:
          cpus: '7'
          memory: 12G

  celery:
    image: celery
    depends_on:
      - mariadb
    volumes:
      - ./celery:/code
    #command: celery -A notebooks/mock/tasks worker --loglevel=info -c 2
  cassandra:
    image: cassandra
    ports:
      - 9042:9042
    #command: cqlsh cassandra -f "create_db.cql"
  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=todos
    #command: python notebooks/create_mariadb.py
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net
  nodejs:
    build: ./server
    ports:
      - 3000:3000
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
networks:
  rabbitmq_go_net:
    driver: bridge
    