version: "3.9"
services:
  pyspark:
    image: jupyter/pyspark-notebook
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./mock:/home/jovyan/mock
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: start-notebook.sh --NotebookApp.token='' # Adiciona a opção aqui
  celery:
    image: celery
    depends_on:
      - mariadb
    volumes:
      - ./celery:/code
    command: celery -A tasks worker --loglevel=info
  cassandra:
    image: cassandra
    ports:
      - 9042:9042
  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=todos
  redis:
    image: redis
    ports:
      - 6379:6379